// Fetch the Chao Phraya daily tide prediction from flood69.peoplesparty.or.th
// (the People's Party flood portal) and write data/flood69.js for the sidebar.
//
// The portal mirrors BMA's KlongMap (สำนักการระบายน้ำ กทม. —
// weather.bangkok.go.th/KlongMap) with a 5-minute cache to spare BMA's system,
// so run this sparingly too. The mirror has no station coordinates (it is a
// schematic), so it cannot feed the canal map — what it adds beyond
// fetch_live.mjs is `dailyheightwater`: today's two high / two low tides in
// metres MSD, which the sidebar shows next to the live water levels.
//
// Like fetch_live.mjs this is a build-time snapshot: the site never calls the
// portal from the browser (no CORS headers on either side).
//
//   node fetch_flood69.mjs
import fs from 'fs';

const BASE = 'https://flood69.peoplesparty.or.th';
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

// ---------- fetch (the site's own order: live proxy first, snapshot second) ----------
async function fetchKlongmap() {
  for (const [path, live] of [['/api/klongmap', true], ['/klong/klongmapdata.json', false]]) {
    for (let attempt = 1; attempt <= 2; attempt++) {
      try {
        const res = await fetch(BASE + path, { headers: { 'User-Agent': UA } });
        if (res.ok) return { data: await res.json(), live };
        console.error(`${path} attempt ${attempt}: HTTP ${res.status}`);
      } catch (e) {
        console.error(`${path} attempt ${attempt}: ${e.cause?.code || e.message}`);
      }
    }
  }
  throw new Error('could not fetch flood69 klongmap data (live proxy and snapshot both failed)');
}

const epoch = d => { // "/Date(1790468040000)/" -> ms
  const m = /\/Date\((-?\d+)\)\//.exec(d || '');
  return m ? +m[1] : null;
};

// ---------- main ----------
const { data, live } = await fetchKlongmap();

// tide prediction: 2 highs + 2 lows per day; the feed uses -99 for "no value",
// and real Gulf tides stay well within ±2 m MSD
const dh = data.dailyheightwater || {};
const events = [
  ['high', epoch(dh.daily_time), dh.hight_water],
  ['high', epoch(dh.night_time), dh.hight_water_pm],
  ['low', epoch(dh.daily_time_low), dh.low_water],
  ['low', epoch(dh.night_time_low), dh.low_water_pm],
].filter(([, at, level]) => at && level != null && Math.abs(level) < 5)
  .map(([type, at, level]) => ({ type, at, level }))
  .sort((a, b) => a.at - b.at);

// station counters are informational only (no coordinates to map them with)
const stations = data.waterStation || [];
const reporting = stations.filter(s => epoch(s.water_level_last?.site_timestamp));
const latestReading = reporting.reduce((a, s) => Math.max(a, epoch(s.water_level_last.site_timestamp)), 0);

const out = {
  fetched_at: Date.now(),
  live_proxy: live, // true = /api/klongmap, false = static snapshot fallback
  source: 'flood69.peoplesparty.or.th · พยากรณ์น้ำขึ้น-น้ำลงจากสำนักการระบายน้ำ กทม. (weather.bangkok.go.th/KlongMap)',
  tide: events.length ? { date: epoch(dh.date_stamp), events } : null,
  stations_total: stations.length,
  stations_reporting: reporting.length,
  latest_reading: latestReading,
};
fs.writeFileSync('data/flood69.js',
  '// generated by fetch_flood69.mjs — do not edit; refresh with `node fetch_flood69.mjs`\n' +
  'window.FLOOD69_STATUS = ' + JSON.stringify(out) + ';\n');

const hm = ms => new Date(ms).toLocaleString('th-TH', { timeZone: 'Asia/Bangkok', hour: '2-digit', minute: '2-digit' });
if (out.tide) {
  const hi = events.filter(e => e.type === 'high');
  const lo = events.filter(e => e.type === 'low');
  const row = e => `${hm(e.at)} (${e.level.toFixed(2)} ม.รทก.)`;
  console.log(`tide ${new Date(out.tide.date).toLocaleDateString('th-TH', { timeZone: 'Asia/Bangkok', dateStyle: 'medium' })}: ` +
    `น้ำขึ้น ${hi.map(row).join(' · ')} — น้ำลง ${lo.map(row).join(' · ')}`);
} else {
  console.log('tide: ไม่มีข้อมูลพยากรณ์ใน feed วันนี้');
}
console.log(`stations reporting: ${reporting.length}/${stations.length} (source: ${live ? 'live proxy' : 'snapshot fallback'})`);
console.log(`wrote data/flood69.js (${Math.round(fs.statSync('data/flood69.js').size / 102.4) / 10} KB)`);
